"""Generates a real, full multi-turn session transcript against the actual
shipped Agent, satisfying the competition's "one demonstrated multi-turn
session" deliverable (see docs/competition_specification.md's "Final
Deliverables" and docs/final_evaluation_faq.md's "Submission and
Demonstration" section).

This is NOT a scripted/fabricated conversation -- it drives the real
`starter.agent.Agent` through the real dialog_policy pipeline, using the
exact same customer-simulator logic (`initial_message`, `customer_reply`,
`materialize_hidden_fields`, `coarse_category`, `normalize_recommendations`)
the official `evaluator.local_evaluator` itself uses, imported directly
rather than reimplemented -- so this transcript is a faithful record of
what the unmodified official evaluator actually produces for this sample,
not a separate/looser demo path. The evaluator module itself is never
modified (per this repo's own "harness is unmodified" convention).

Usage:
    python3 scripts/generate_demo_transcript.py [--sample-id public_0002] [--output PATH]
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from evaluator.local_evaluator import (
    MAX_TURNS,
    TOP_K,
    catalog_index,
    coarse_category,
    customer_reply,
    initial_message,
    load_jsonl,
    materialize_hidden_fields,
    normalize_recommendations,
)
from starter.agent import Agent

ROOT = Path(__file__).resolve().parent.parent


def run_transcript(sample: dict, catalog_ids: set, categories: dict, products: dict) -> dict:
    agent = Agent()
    session_id = f"demo_{sample['sample_id']}"
    agent.reset(session_id, sample["user_profile"])
    target = str(sample["ground_truth"]["parent_asin"])
    target_title = products.get(target, {}).get("title", "(title unavailable)")
    effective_intent_card, effective_behavior = materialize_hidden_fields(sample, products)
    effective_sample = {**sample, "intent_card": effective_intent_card, "behavior": effective_behavior}

    disclosed: set = set()
    boundary_used = False
    override_applied = sample["scenario_type"] != "intent_override"
    user_message = initial_message(effective_sample, coarse_category(categories.get(target, [])), disclosed)

    turns = []
    hit_turn = None
    best_rank = None
    for turn in range(1, MAX_TURNS + 1):
        response = agent.respond(session_id, user_message, turn, TOP_K)
        ranked = normalize_recommendations(response.get("recommendations"), catalog_ids)
        rec_titles = [
            {"parent_asin": asin, "title": products.get(asin, {}).get("title", "(title unavailable)")}
            for asin in ranked[:5]
        ]
        is_hit = override_applied and target in ranked
        rank_if_present = ranked.index(target) + 1 if target in ranked else None
        turns.append({
            "turn": turn,
            "user_message": user_message,
            "agent_message": response.get("message"),
            "ask_attribute": response.get("ask_attribute"),
            "top_recommendations": rec_titles,
            "target_rank_this_turn": rank_if_present,
            "usage": response.get("usage"),
            "hit": is_hit,
        })
        if is_hit:
            hit_turn = turn
            best_rank = rank_if_present
            break
        if turn == MAX_TURNS:
            break
        override = effective_sample.get("behavior", {}).get("override") or {}
        if not override_applied and turn + 1 == int(override.get("turn", 3)):
            override_applied = True
            new_value = str(override.get("new_value", ""))
            if new_value:
                disclosed.add(new_value)
            user_message = str(override.get("message", "Actually, please ignore my earlier preference."))
        else:
            user_message, boundary_used = customer_reply(
                effective_sample, response.get("ask_attribute"), disclosed, boundary_used
            )

    return {
        "sample_id": sample["sample_id"],
        "scenario_type": sample["scenario_type"],
        "target_parent_asin": target,
        "target_title": target_title,
        "hit_turn": hit_turn,
        "best_rank": best_rank,
        "turns": turns,
    }


def render_markdown(result: dict) -> str:
    lines = [
        f"# Demo transcript: `{result['sample_id']}` ({result['scenario_type']})",
        "",
        "Generated by `scripts/generate_demo_transcript.py` against the real, shipped "
        "`starter.agent.Agent` (frozen cross-encoder reranking enabled, its default "
        "configuration) -- not a scripted or fabricated conversation. Uses the same "
        "customer-simulator functions the unmodified official evaluator itself uses.",
        "",
        f"**Target product:** {result['target_title']} (`{result['target_parent_asin']}`)",
        "",
    ]
    if result["hit_turn"] is not None:
        lines.append(f"**Result: HIT on turn {result['hit_turn']}, rank {result['best_rank']}.**")
    else:
        lines.append(f"**Result: not recovered within {MAX_TURNS} turns.**")
    lines.append("")
    lines.append("---")
    for t in result["turns"]:
        lines.append("")
        lines.append(f"### Turn {t['turn']}")
        lines.append("")
        lines.append(f"**Shopper:** {t['user_message']}")
        lines.append("")
        agent_line = f"**Agent:** {t['agent_message']}"
        if t["ask_attribute"]:
            agent_line += f"  *(asking about: `{t['ask_attribute']}`)*"
        lines.append(agent_line)
        lines.append("")
        if t["top_recommendations"]:
            lines.append("Top recommendations this turn:")
            for i, rec in enumerate(t["top_recommendations"], start=1):
                marker = " **← target**" if rec["parent_asin"] == result["target_parent_asin"] else ""
                lines.append(f"{i}. {rec['title']} (`{rec['parent_asin']}`){marker}")
        else:
            lines.append("*(no recommendations returned this turn -- clarifying question only)*")
        usage = t.get("usage") or {}
        if usage.get("prompt_tokens") or usage.get("completion_tokens"):
            lines.append("")
            lines.append(f"*LLM usage this turn: {usage.get('prompt_tokens', 0)} prompt / {usage.get('completion_tokens', 0)} completion tokens.*")
        if t["hit"]:
            lines.append("")
            lines.append(f"**✅ Target hit at rank {t['target_rank_this_turn']} -- session ends here.**")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--sample-id", default="public_0002")
    parser.add_argument("--catalog", default="data/catalog.jsonl")
    parser.add_argument("--dataset", default="data/public_set.jsonl")
    parser.add_argument("--output", default="docs/demo_transcript.md")
    args = parser.parse_args()

    samples = load_jsonl(ROOT / args.dataset)
    sample = next((s for s in samples if s["sample_id"] == args.sample_id), None)
    if sample is None:
        raise SystemExit(f"No sample with sample_id={args.sample_id!r} in {args.dataset}")

    catalog_ids, categories, products = catalog_index(ROOT / args.catalog)

    result = run_transcript(sample, catalog_ids, categories, products)
    markdown = render_markdown(result)

    output_path = ROOT / args.output
    output_path.write_text(markdown, encoding="utf-8")
    print(f"Wrote transcript for {args.sample_id} ({result['scenario_type']}) to {output_path}")
    print(f"Result: {'HIT on turn ' + str(result['hit_turn']) + ', rank ' + str(result['best_rank']) if result['hit_turn'] else 'not recovered'}")

    # Also dump the raw structured result for anyone who wants to inspect it
    # programmatically rather than read the rendered markdown.
    (output_path.with_suffix(".json")).write_text(json.dumps(result, indent=2), encoding="utf-8")


if __name__ == "__main__":
    main()
